### ISSUE TITLE
jinja2.exceptions.TemplateNotFound: index.html when using docker

### ISSUE THREAD

**Issue by imehrez** [oitsjustjose/Flask-OpenCV-Streamer#2]
The streamer works just fine when  i run my code normaly, but when i run it inside a docekr container i get

>  jinja2.exceptions.TemplateNotFound: index.html

and i can't see the stream.

The thing is i am not sure where exactly does the streamer gets the template index.html. when i start a shell inside the container i can see the correct hirrarchy
- app
   --test.py
   -templates
       -- index.html

Here is the complete **error stack**
`image_server_1  |  * Serving Flask app "flask_opencv_streamer.streamer_3030" (lazy loading)
image_server_1  |  * Environment: production
image_server_1  |    WARNING: This is a development server. Do not use it in a production deployment.
image_server_1  |    Use a production WSGI server instead.
image_server_1  |  * Debug mode: off
image_server_1  |  * Running on http://0.0.0.0:3030/ (Press CTRL+C to quit)
image_server_1  | [2019-06-24 12:15:39,255] ERROR in app: Exception on / [GET]
image_server_1  | Traceback (most recent call last):
image_server_1  |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2311, in wsgi_app
image_server_1  |     response = self.full_dispatch_request()
image_server_1  |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1834, in full_dispatch_request
image_server_1  |     rv = self.handle_user_exception(e)
image_server_1  |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1737, in handle_user_exception
image_server_1  |     reraise(exc_type, exc_value, tb)
image_server_1  |   File "/usr/local/lib/python3.7/site-packages/flask/_compat.py", line 36, in reraise
image_server_1  |     raise value
image_server_1  |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1832, in full_dispatch_request
image_server_1  |     rv = self.dispatch_request()
image_server_1  |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1818, in dispatch_request
image_server_1  |     return self.view_functions[rule.endpoint](**req.view_args)
image_server_1  |   File "/usr/local/lib/python3.7/site-packages/flask_opencv_streamer/streamer.py", line 213, in decorated
image_server_1  |     return func(*args, **kwargs)
image_server_1  |   File "/usr/local/lib/python3.7/site-packages/flask_opencv_streamer/streamer.py", line 89, in index
image_server_1  |     return render_template("index.html")
image_server_1  |   File "/usr/local/lib/python3.7/site-packages/flask/templating.py", line 134, in render_template
image_server_1  |     return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
image_server_1  |   File "/usr/local/lib/python3.7/site-packages/jinja2/environment.py", line 869, in get_or_select_template
image_server_1  |     return self.get_template(template_name_or_list, parent, globals)
image_server_1  |   File "/usr/local/lib/python3.7/site-packages/jinja2/environment.py", line 830, in get_template
image_server_1  |     return self._load_template(name, self.make_globals(globals))
image_server_1  |   File "/usr/local/lib/python3.7/site-packages/jinja2/environment.py", line 804, in _load_template
image_server_1  |     template = self.loader.load(self, name, globals)
image_server_1  |   File "/usr/local/lib/python3.7/site-packages/jinja2/loaders.py", line 113, in load
image_server_1  |     source, filename, uptodate = self.get_source(environment, name)
image_server_1  |   File "/usr/local/lib/python3.7/site-packages/flask/templating.py", line 58, in get_source
image_server_1  |     return self._get_source_fast(environment, template)
image_server_1  |   File "/usr/local/lib/python3.7/site-packages/flask/templating.py", line 86, in _get_source_fast
image_server_1  |     raise TemplateNotFound(template)
image_server_1  | jinja2.exceptions.TemplateNotFound: index.html`

and **Dockerfile** 

`FROM python:3.7-slim

copy . /app
COPY templates /app/
Expose 3030
RUN pip install numpy flask_opencv_streamer
# install opencv
CMD ["python3","/app/test.py"]
`

**Comment by oitsjustjose** [comment]
So, the hierarchy is:

```
Project Directory <folder>
↳ app.py <file>
  templates <folder>
  ↳ index.html <file>
```

Not sure if this helps, but assuming that it works when not in the Docker container, it may be that the Docker container is putting you in some directory that isn't where your files are, and then running from there. I'll try to fix this at some point, but it sounds like my relative file locations aren't working so switch to absolute and see if that helps.

**Comment by imehrez** [comment]
Thank you i got it fixed.
The problem was that flask was looking in the root directory and i thought it would look recurcively but looks like it didn't

So I added

`WORKDIR /app`

before the CMD command in the Dockerfile and it worked perfectly

**Comment by iqrammm** [comment]
Sorry for barging in,I would like to ask since I suppose you actually managed to figure out this part where I cant import the package,Below is a snapshot is my error. I am hopeful you will be kind enough to assist me.
![Screenshot from 2019-08-12 19-28-41](https://user-images.githubusercontent.com/48657762/62862087-dd96a880-bd37-11e9-911e-d2144a386250.png)
